//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScudExporterDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int ID { get; set; }
        public int Gtype { get; set; }
        public Nullable<int> GTypeCodeAdd { get; set; }
        public int Config { get; set; }
        public string CodeP { get; set; }
        public string CodePAdd { get; set; }
        public Nullable<int> Status { get; set; }
        public int Owner { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> GrStatus { get; set; }
        public int GroupID { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public string fingertemplate { get; set; }
    }
}
