//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScudExporterDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScudExporter : DbContext
    {
        public ScudExporter()
            : base("name=ScudExporter")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Division> PDivision { get; set; }
        public virtual DbSet<Emp> pList { get; set; }
        public virtual DbSet<Events> pLogData { get; set; }
        public virtual DbSet<Cards> pMark { get; set; }
    }
}
