//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScudExporter.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScudEvent
    {
        public System.DateTime TimeVal { get; set; }
        public Nullable<int> NumCom { get; set; }
        public Nullable<int> IDComp { get; set; }
        public Nullable<int> Par1 { get; set; }
        public Nullable<int> Par2 { get; set; }
        public Nullable<int> Par3 { get; set; }
        public Nullable<int> Par4 { get; set; }
        public int Event { get; set; }
        public Nullable<int> IndexKey { get; set; }
        public Nullable<int> RazdIndex { get; set; }
        public Nullable<int> HozOrgan { get; set; }
        public Nullable<int> HozGuest { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DoorIndex { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<System.DateTime> DeviceTime { get; set; }
        public Nullable<int> VEvent { get; set; }
        public Nullable<int> ZReserv { get; set; }
        public Nullable<int> ZoneIndex { get; set; }
        public Nullable<int> ReaderIndex { get; set; }
        public Nullable<int> Sign { get; set; }
        public Nullable<int> tpRzdIndex { get; set; }
        public Nullable<int> tpPar4 { get; set; }
        public Nullable<int> IndexZone { get; set; }
        public Nullable<int> tpIndex { get; set; }
        public System.Guid GUID { get; set; }
    }
}
